#!/bin/bash

i=1
j=1000000
FILE_NUM=99
while [ $i -le $FILE_NUM ]
do
    name=`printf "../plaintexts/%02d.txt" $i`
    echo $name
    base64 /dev/urandom | head -c $j > $name
    j=`expr $j - 10000`
    let i++
done
